export interface IFamilyPatient {
	updatedByUser: any
	createdByUser: any
	medicalRecord: any
	userForms: any[]
	healthCareUserForms: any
	mainForm: any
	isCreate: boolean
	dobDisplay: string
	bloodPressureDisplay: string
	riskColor: string
	patientDangerousDisplay: string
	patientFamilies: any
	formTemplates: any
	bmiValue: number
	medicalRecords: any[]
	doctorManagerId: number
	monitoringDoctorId: any
	nursingCareId: any
	id: number
	name: string
	dateOfBirth: string
	gender: number
	risk: number
	email: string
	phone: string
	bloodPressure: number
	departmentId?: number
	hi?: string
	address?: string
	healthPackageId: any
	height: number
	weight: number
	bmi: number
	qrUrl: any
	createdByUserId: any
	updatedByUserId: any
	updatedAt: string
	createdAt: string
	isActive: boolean
	isDeleted: boolean
	avatarUrl: string
}

export interface IFamilyRequest {
	updatedByUser: any
	createdByUser: any
	toPatient: any
	fromPatient: FromPatient
	invitationStatusDisplay: string
	patientFamilyId: number
	toPatientId: number
	fromPatientId: number
	familyInvitationStatus: number
	createdByUserId: any
	updatedByUserId: any
	updatedAt: string
	createdAt: string
	isActive: boolean
	isDeleted: boolean
}

export interface FromPatient {
	updatedByUser: any
	createdByUser: any
	medicalRecord: any
	userForms: any[]
	healthCareUserForms: any
	mainForm: any
	isCreate: boolean
	dobDisplay: string
	bloodPressureDisplay: string
	riskColor: string
	patientDangerousDisplay: string
	patientFamilies: any
	formTemplates: any
	bmiValue: number
	medicalRecords: any[]
	doctorManagerId: number
	monitoringDoctorId: any
	nursingCareId: any
	id: number
	name: string
	dateOfBirth: string
	gender: number
	risk: number
	email: string
	phone: string
	bloodPressure: number
	departmentId: any
	hi: any
	address: string
	healthPackageId: any
	height: number
	weight: number
	bmi: number
	qrUrl: any
	createdByUserId: any
	updatedByUserId: any
	updatedAt: string
	createdAt: string
	isActive: boolean
	isDeleted: boolean
	avatarUrl: string
}
